---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos7

suites:
  - name: default
    run_list:
      - recipe[mesos_master::default]
    attributes:
