name 'mesos_master'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mesos_master'
long_description 'Installs/Configures mesos_master'
version '0.1.0'
